#!/bin/bash
#Install Bind9 DNS Server Pada Raspbian
#Jika Ada Error Hubungi saya@rifky.tech

#Install BIND9
sudo apt-get -y install bind9

#Edit /etc/bind/named.conf.local
rm -rf /etc/bind/named.conf.local
cp -r named.conf.local /etc/named.conf.local

#creat db domain
cp -r db.dom /etc/bind/

#Creat db ip
cp -r db.i[ /etc/bind/
